'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {safeSlug,writeJson,readJson,sha256File}=require('../electron/core/fs-utils.cjs');
const {redact,redactString}=require('../electron/core/redaction.cjs');
const {BridgeError,asBridgeError}=require('../electron/core/errors.cjs');
const {SecurityService}=require('../electron/services/security-service.cjs');
const service=()=>new SecurityService({logger:{info(){}},emit(){}});
test('01 slug removes accents',()=>assert.equal(safeSlug('Ágil Hub — Projeto 2026'),'agil-hub-projeto-2026'));
test('02 slug fallback',()=>assert.equal(safeSlug('***','fallback'),'fallback'));
test('03 redacts github token',()=>assert.equal(redactString('ghp_abcdefghijklmnopqrstuvwxyz123456'),'[REDACTED]'));
test('04 redacts sensitive keys',()=>assert.equal(redact({password:'secret'}).password,'[REDACTED]'));
test('05 BridgeError preserves code',()=>assert.equal(new BridgeError('X','x').code,'X'));
test('06 converts Error',()=>assert.equal(asBridgeError(new Error('x')).message,'x'));
test('07 write/read json',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));const p=path.join(d,'x.json');await writeJson(p,{a:1});assert.deepEqual(await readJson(p),{a:1});await fs.rm(d,{recursive:true,force:true});});
test('08 json fallback',async()=>assert.deepEqual(await readJson('/missing',[]),[]));
test('09 sha256 deterministic',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));const p=path.join(d,'x');await fs.writeFile(p,'abc');assert.equal((await sha256File(p)).length,64);await fs.rm(d,{recursive:true,force:true});});
test('10 sanitize env',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'.env'),'API_URL=x\nSECRET=y\n');const r=await service().sanitize(d);assert.ok(r.removed.includes('.env'));assert.match(await fs.readFile(path.join(d,'.env.example'),'utf8'),/API_URL=/);await fs.rm(d,{recursive:true,force:true});});
test('11 scan github token',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'x.js'),'ghp_abcdefghijklmnopqrstuvwxyz123456');const r=await service().scan(d);assert.ok(r.blocking.length);await fs.rm(d,{recursive:true,force:true});});
test('12 scan private key',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'x'),'-----BEGIN PRIVATE KEY-----');assert.ok((await service().scan(d)).blocking.length);await fs.rm(d,{recursive:true,force:true});});
test('13 safe scan',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'x'),'hello');assert.equal((await service().scan(d)).blocking.length,0);await fs.rm(d,{recursive:true,force:true});});
test('14 tree counts files',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'x'),'a');assert.equal((await service().validateExportTree(d)).files,1);await fs.rm(d,{recursive:true,force:true});});
test('15 tree enforces file limit',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'x'),'a');await assert.rejects(()=>service().validateExportTree(d,{maxFiles:0}));await fs.rm(d,{recursive:true,force:true});});
test('16 detects sdk',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.writeFile(path.join(d,'x.js'),'require("@base44/sdk")');assert.equal((await service().analyzeBase44Dependencies(d)).sdkImports,1);await fs.rm(d,{recursive:true,force:true});});
test('17 detects entity',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.mkdir(path.join(d,'base44','entities'),{recursive:true});await fs.writeFile(path.join(d,'base44','entities','Task.jsonc'),'{}');assert.equal((await service().analyzeBase44Dependencies(d)).entityFiles.length,1);await fs.rm(d,{recursive:true,force:true});});
test('18 sanitizer removes node_modules',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'rb-'));await fs.mkdir(path.join(d,'node_modules'));await fs.writeFile(path.join(d,'node_modules','x'),'a');await service().sanitize(d);await assert.rejects(fs.access(path.join(d,'node_modules')));await fs.rm(d,{recursive:true,force:true});});
test('19 repository name max length',()=>assert.ok(safeSlug('a'.repeat(200)).length<=80));
