'use strict';
const $=(id)=>document.getElementById(id); const log=(text)=>{ $('log').textContent+=`${text}\n`; $('log').scrollTop=$('log').scrollHeight; };
async function call(promise){ const result=await promise; if(!result.ok) throw Object.assign(new Error(result.error.message),result.error); return result.data; }
async function load(){ try{ const status=await call(window.rbBridge.system.status()); $('base44Status').textContent=status.base44?.loggedIn?'Conectado':'Não conectado'; $('githubStatus').textContent=status.github?.authenticated?'Conectado':'Não conectado'; if(status.base44?.loggedIn) await projects(); if(status.github?.authenticated) await accounts(); }catch(e){log(e.message);} }
async function projects(){ const list=await call(window.rbBridge.base44.projects()); $('project').innerHTML=list.map(p=>`<option value="${p.id}" data-name="${p.name.replaceAll('"','&quot;')}">${p.name}</option>`).join(''); }
async function accounts(){ const data=await call(window.rbBridge.github.accounts()); $('owner').innerHTML=data.accounts.map(a=>`<option value="${a.login}" data-type="${a.type}">${a.label}</option>`).join(''); }
$('base44Login').onclick=async()=>{try{log('Abrindo autorização Base44...');await call(window.rbBridge.base44.login());$('base44Status').textContent='Conectado';await projects();}catch(e){log(e.message);}};
$('githubLogin').onclick=async()=>{try{log('Abrindo autorização GitHub...');await call(window.rbBridge.github.login());$('githubStatus').textContent='Conectado';await accounts();}catch(e){log(e.message);}};
$('chooseOutput').onclick=async()=>{const value=await call(window.rbBridge.system.chooseOutputDirectory());if(value)$('output').value=value;};
$('cancel').onclick=async()=>{await call(window.rbBridge.migration.cancel());log('Cancelamento solicitado.');};
$('start').onclick=async()=>{try{const projectOption=$('project').selectedOptions[0],ownerOption=$('owner').selectedOptions[0];if(!projectOption||!ownerOption)throw new Error('Conecte as contas e selecione projeto e destino.');$('result').textContent='';const input={acceptedAuthorization:$('authorization').checked,project:{id:projectOption.value,name:projectOption.dataset.name},outputDirectory:$('output').value,buildValidation:$('buildValidation').checked,repository:{owner:ownerOption.value,ownerType:ownerOption.dataset.type,name:$('repoName').value||projectOption.dataset.name,description:$('description').value,visibility:$('publicRepo').checked?'public':'private',commitMessage:'Migração inicial do Base44'}};log('Migração iniciada...');const result=await call(window.rbBridge.migration.start(input));$('result').className='success';$('result').textContent=`Concluído: ${result.github.fullName} (${result.github.sha.slice(0,7)})`;if(result.github.url)await call(window.rbBridge.system.openExternal(result.github.url));}catch(e){$('result').className='error';$('result').textContent=e.message;log(`ERRO: ${e.message}`);}};
for(const channel of ['base44:output','github:output','build:output','migration:progress','toolchain:progress'])window.rbBridge.on(channel,(event)=>log(event.text||event.message||JSON.stringify(event)));
load();
